language: c
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake openjdk-7-jdk autotools-dev libltdl-dev libtool autoconf autopoint libboost-all-dev
  - sudo apt-get -qq install genromfs zfs-fuse autoconf ant libffi-dev ruby bison gyp git build-essential
  - sudo apt-get -qq install qemu-utils qemu-kvm bridge-utils libvirt0 libvirt-bin
  - cd ../
  - mkdir libuv
  - cd libuv
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libuv-dev_0.10.18-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libuv0.10-dbg_0.10.18-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libuv0.10_0.10.18-1_amd64.deb
  - sudo dpkg -i libuv*.deb
script: 
  - ./build.sh
