language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake openjdk-7-jdk autotools-dev libltdl-dev libtool autoconf autopoint libboost-all-dev
  - sudo apt-get -qq install genromfs zfs-fuse autoconf ant libffi-dev ruby bison gyp git build-essential
  - sudo apt-get -qq install qemu-kvm bridge-utils libvirt0 libvirt-bin
  - sudo apt-get -qq install g++-4.8
  - wget http://launchpadlibrarian.net/155499889/qemu-utils_1.5.0%2Bdfsg-3ubuntu5.1_i386.deb
  - sudo dpkg -i qemu-utils*.deb
  - cd ../
  - mkdir libuv
  - cd libuv
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libuv-dev_0.10.18-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libuv0.10-dbg_0.10.18-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libuv0.10_0.10.18-1_amd64.deb
  - sudo dpkg -i libuv*.deb
  - cd ../uosv
script: 
  - ./build.sh CC=gcc-4.8 CXX=g++-4.8
